# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pablo\PycharmProjects\pythonProject\ui\sql_server.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(230, 190)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(230, 190))
        Dialog.setMaximumSize(QtCore.QSize(230, 190))
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(16, 10, 201, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEditUser = QtWidgets.QLineEdit(self.widget)
        self.lineEditUser.setInputMask("")
        self.lineEditUser.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditUser.setObjectName("lineEditUser")
        self.gridLayout.addWidget(self.lineEditUser, 1, 1, 1, 1)
        self.labelHost = QtWidgets.QLabel(self.widget)
        self.labelHost.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelHost.setObjectName("labelHost")
        self.gridLayout.addWidget(self.labelHost, 0, 0, 1, 1)
        self.lineEditPassword = QtWidgets.QLineEdit(self.widget)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.gridLayout.addWidget(self.lineEditPassword, 2, 1, 1, 1)
        self.labelUser = QtWidgets.QLabel(self.widget)
        self.labelUser.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelUser.setObjectName("labelUser")
        self.gridLayout.addWidget(self.labelUser, 1, 0, 1, 1)
        self.labelPassword = QtWidgets.QLabel(self.widget)
        self.labelPassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout.addWidget(self.labelPassword, 2, 0, 1, 1)
        self.lineEditHost = QtWidgets.QLineEdit(self.widget)
        self.lineEditHost.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditHost.setObjectName("lineEditHost")
        self.gridLayout.addWidget(self.lineEditHost, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.pushButtonConnect = QtWidgets.QPushButton(self.widget)
        self.pushButtonConnect.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.verticalLayout.addWidget(self.pushButtonConnect)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "SQL Server"))
        self.lineEditUser.setText(_translate("Dialog", "root"))
        self.labelHost.setText(_translate("Dialog", "Host:"))
        self.lineEditPassword.setText(_translate("Dialog", "cimne2020"))
        self.labelUser.setText(_translate("Dialog", "User:"))
        self.labelPassword.setText(_translate("Dialog", "Password:"))
        self.lineEditHost.setText(_translate("Dialog", "localhost"))
        self.pushButtonConnect.setText(_translate("Dialog", "Connect"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
